### ISSUE TITLE
altair version issue (it wants 4.0.0, but I can only get 5.0.1) preventing initial run after installation

### ISSUE THREAD

**Issue by vickerse1** [YttriLab/A-SOID#38]
Hi,

On Windows 10, my installation hangs after running:

conda env create --file asoid.yml

I get a message telling me to upgrade conda from 34.8.3 to 22.9.0, then it says "done" after preparing, verifying, and executing, but never returns me to the command line.

Then, when I open new anaconda prompt, activate the environment, and run:

pip install .

...it seems to work. However, when I then type "asoid app" to run it, I get the following error:

----------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\asoid_b\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\asoid_b\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\asoid_b\Scripts\asoid.exe\__main__.py", line 4, in <module>
  File "C:\ProgramData\Anaconda3\envs\asoid_b\lib\site-packages\asoid\__main__.py", line 2, in <module>
    import streamlit.cli
  File "C:\ProgramData\Anaconda3\envs\asoid_b\lib\site-packages\streamlit\__init__.py", line 70, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "C:\ProgramData\Anaconda3\envs\asoid_b\lib\site-packages\streamlit\delta_generator.py", line 90, in <module>
    from streamlit.elements.arrow_altair import ArrowAltairMixin
  File "C:\ProgramData\Anaconda3\envs\asoid_b\lib\site-packages\streamlit\elements\arrow_altair.py", line 27, in <module>
    from altair.vegalite.v4.api import Chart
ModuleNotFoundError: No module named 'altair.vegalite.v4'
----------------------

I've tried several times to go back and specify altair==v 4.0.0 in the requirements.txt file, and it doesn't seem to work (I always end up with 5.0.1).

Can you help me with this?

Thanks,

Evan

Evan

**Comment by JensBlack** [comment]
Hi Evan,

thanks for reporting this. It seems that the library had a big update in may and our fixed streamlit version is not coping with it very well. [Link](https://discuss.streamlit.io/t/modulenotfounderror-no-module-named-altair-vegalite-v4/42921).

I pushed a fixed altair version for both requirements.txt and setup.py. If you download it again everything should work as planned.

To save you some trouble, manually installing this also fixes the problem:

```
pip install altair~=4.1.0
```

You are welcome to reopen the issue if it still persists, but it works on my side.

**Comment by vickerse1** [comment]
Hi Jens,

OK thanks this worked.

-Evan
________________________________
