### ISSUE TITLE
Extract Features TypingError 

### ISSUE THREAD

**Issue by brian1000** [YttriLab/A-SOID#50]
Hello!

I'm trying to do a small test with my sample video to go through the entire A-Soid pipeline. I'm already stuck at the extract features step with the following error: 
```
TypingError: Failed in nopython mode pipeline (step: nopython frontend) [1m[1mnon-precise type reflected list(array(pyobject, 2d, C))<iv=None>[0m [0m[1mDuring: typing of argument at C:\Users\emricklab\anaconda3\envs\asoid-test\lib\site-packages\asoid\utils\extract_features.py (153)[0m [1m File "anaconda3\envs\asoid-test\lib\site-packages\asoid\utils\extract_features.py", line 153:[0m [1mdef fast_smooth(data, n): <source elided> [1m@jit(nopython=True) [0m[1m^[0m[0m
Traceback:
File "C:\Users\emricklab\anaconda3\envs\asoid-test\lib\site-packages\streamlit\scriptrunner\script_runner.py", line 557, in _run_script
    exec(code, module.__dict__)
File "C:\Users\emricklab\anaconda3\envs\asoid-test\lib\site-packages\asoid\app.py", line 332, in <module>
    main()
File "C:\Users\emricklab\anaconda3\envs\asoid-test\lib\site-packages\asoid\app.py", line 328, in main
    application_function()
File "C:\Users\emricklab\anaconda3\envs\asoid-test\lib\site-packages\asoid\apps\B_extract_features.py", line 101, in main
    extractor.main()
File "C:\Users\emricklab\anaconda3\envs\asoid-test\lib\site-packages\asoid\utils\extract_features.py", line 522, in main
    self.extract_features()
File "C:\Users\emricklab\anaconda3\envs\asoid-test\lib\site-packages\asoid\utils\extract_features.py", line 469, in extract_features
    self.features, self.scaled_features = feature_extraction(self.processed_input_data,
File "C:\Users\emricklab\anaconda3\envs\asoid-test\lib\site-packages\asoid\utils\extract_features.py", line 198, in feature_extraction
    binned_features = bsoid_extract_numba([train_datalist[i]], framerate)
File "C:\Users\emricklab\anaconda3\envs\asoid-test\lib\site-packages\asoid\utils\extract_features.py", line 189, in bsoid_extract_numba
    features = fast_feature_extraction(data, fps, index * 2, smooth)
File "C:\Users\emricklab\anaconda3\envs\asoid-test\lib\site-packages\numba\core\dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
File "C:\Users\emricklab\anaconda3\envs\asoid-test\lib\site-packages\numba\core\dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
```
A-Soid Installation: 
I git cloned the repo, used the setup.py
**I had an error building all asoid packages (hdbscan)**
I used: `conda install -c conda-forge hdbscan` in my anaconda venv and then updated A-Soid and everything was successfully built. 

My config: 
```
[Project]
PROJECT_TYPE = DeepLabCut
PROJECT_NAME = Jul-24-2023
PROJECT_PATH = C:\Users\emricklab/Desktop/asoid_output
FRAMERATE = 30
KEYPOINTS_CHOSEN = snout, earL, earR, bodyR, bodyM, bodyL, tailB
EXCLUDE_OTHER = False
FILE_TYPE = csv
INDIVIDUALS_CHOSEN = single animal
CLASSES = left, right, other
MULTI_ANIMAL = False

[Data]
DATA_INPUT_FILES = test1DLC_resnet50_BreadJun2shuffle1_400000.csv
LABEL_INPUT_FILES = binary_test1_mouse836.csv
ROOT_PATH = None

[Processing]
ITERATION = 0
N_SHUFFLED_SPLITS = 10
MIN_DURATION = 0.1
TRAIN_FRACTION = 0.01
MAX_ITER = 100
MAX_SAMPLES_ITER = 20
N_SHUFFLED_SPLIT = 10
```

Below I've attached the output from DLC and my binary events for this 30s sample video. 
All behaviors (move left, move right) show up in the binary event csv. 
I have not changed anything in the structure of the DLC output csv.
[binary_test1_mouse836.csv](https://github.com/YttriLab/A-SOID/files/12152381/binary_test1_mouse836.csv)
[test1DLC_resnet50_BreadJun2shuffle1_400000.csv](https://github.com/YttriLab/A-SOID/files/12152382/test1DLC_resnet50_BreadJun2shuffle1_400000.csv)

Please let me know what else you need from me in order to help me troubleshoot this issue. I'd really like to work with your software!

My A-Soid version is: 0.2.5b0, python: 3.8.17. 
system: Windows 10

**Comment by brian1000** [comment]
I've attempted to solve the issue by taking out the @jit(nopython=True) in the extract_features.py for the fast_smooth() function but this only led to me getting the same exact error for the next function that uses @jit(nopython=True). So I'm not sure if I'm missing something; i have numba 0.57.1 on this venv so I don't think its a version issue. Any help would still be appreciated.

**Comment by JensBlack** [comment]
The first thing I noticed is that your binary file does not start with time = 0.0 but with 1.136. This shouldn't be an issue for A-SOiD but could be a mismatch when your pose estimation starts at 0.0. If this is a Boris export, you can alter the export to include the entire video, not just your observations with labels present. (which includes the first 1.136 sec in which no label is present).

However, converting the time column into the more common [0.0, 0.1, 0.2, ...] format did not solve the issue on my side, so I am guessing this is, as you previously said, an issue with numba.

I am summoning our resident numba expert @runninghsus :). Please have a look.

In the meantime, would you @brian1000 be so kind and test A-SOiD with the CalMS21 data set as well and report back whether this is working out for you? Thanks!

**Comment by brian1000** [comment]
@JensBlack forgive me for the rudimentary question but how do I get the (.npy) train/test files from the CalMS21 paper? I navigated to this area: 
![image](https://github.com/YttriLab/A-SOID/assets/22827738/dab3aff4-0a7d-4373-af95-57d633d345ef)
and downloaded the task1_MARS_features.zip file. However, inside all the train/test files are stored in the .npz format, not .npy format. Am I supposed to preprocess the files further before inserting them into asoid? I get this error when setting paths to the .npz files: 
![image](https://github.com/YttriLab/A-SOID/assets/22827738/cced918d-8f27-4d21-bca0-779b56b51448)

**Comment by brian1000** [comment]
Hello @JensBlack & @runninghsus, I was able to successfully perform the extract features step using the test/train calms21 .npy files. 
![image](https://github.com/YttriLab/A-SOID/assets/22827738/5e13adb2-37e4-4296-b9bb-6f8d1c9e99fc)

**Comment by JensBlack** [comment]
Thanks for investigating. I will discuss this with @runninghsus in our next meeting and come back to you.

If you are exporting the CSVs directly from DLC, there should not be an issue with them. Float should be fine.
It might be an issue with your Boris export, but I am not sure why yet.

**Comment by Yiijee** [comment]
Hello, 

I tried to run a test dataset from SLEAP website: [flies13](https://sleap.ai/datasets.html) and ran into the same issue. I attached the h5 pose-tracking results and binary annotation from Boris here:
[SLEAP_flies13.zip](https://github.com/YttriLab/A-SOID/files/12316965/SLEAP_flies13.zip)

We got the same error in GUI at extracting features step as @brian1000 posted, and here is the complete output in the terminal just incase it can provide more information:
```
2023-08-10 15:48:14.948 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\clowneylab\.conda\envs\asoid-test\lib\site-packages\streamlit\legacy_caching\caching.py", line 539, in get_or_create_cached_value
    return_value = _read_from_cache(
  File "C:\Users\clowneylab\.conda\envs\asoid-test\lib\site-packages\streamlit\legacy_caching\caching.py", line 338, in _read_from_cache
    raise e
  File "C:\Users\clowneylab\.conda\envs\asoid-test\lib\site-packages\streamlit\legacy_caching\caching.py", line 323, in _read_from_cache
    return _read_from_mem_cache(
  File "C:\Users\clowneylab\.conda\envs\asoid-test\lib\site-packages\streamlit\legacy_caching\caching.py", line 241, in _read_from_mem_cache
    raise CacheKeyNotFoundError("Key not found in mem cache")
streamlit.legacy_caching.caching.CacheKeyNotFoundError: Key not found in mem cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\clowneylab\asoid\asoid\apps\B_extract_features.py", line 78, in main
    [_, _, _, _] = load_features(working_dir, prefix)
  File "C:\Users\clowneylab\.conda\envs\asoid-test\lib\site-packages\streamlit\legacy_caching\caching.py", line 573, in wrapped_func
    return get_or_create_cached_value()
  File "C:\Users\clowneylab\.conda\envs\asoid-test\lib\site-packages\streamlit\legacy_caching\caching.py", line 557, in get_or_create_cached_value
    return_value = func(*args, **kwargs)
  File "c:\users\clowneylab\asoid\asoid\utils\load_workspace.py", line 54, in load_features
    data = _load_sav(path, name, 'feats_targets.sav')
  File "c:\users\clowneylab\asoid\asoid\utils\load_workspace.py", line 9, in _load_sav
    with open(os.path.join(path, name, filename), 'rb') as fr:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\clowneylab/Desktop/asoid_output\\Aug-10-2023\\feats_targets.sav'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\clowneylab\.conda\envs\asoid-test\lib\site-packages\streamlit\scriptrunner\script_runner.py", line 557, in _run_script
    exec(code, module.__dict__)
  File "c:\users\clowneylab\asoid\asoid\app.py", line 332, in <module>
    main()
  File "c:\users\clowneylab\asoid\asoid\app.py", line 328, in main
    application_function()
  File "c:\users\clowneylab\asoid\asoid\apps\B_extract_features.py", line 101, in main
    extractor.main()
  File "c:\users\clowneylab\asoid\asoid\utils\extract_features.py", line 522, in main
    self.extract_features()
  File "c:\users\clowneylab\asoid\asoid\utils\extract_features.py", line 469, in extract_features
    self.features, self.scaled_features = feature_extraction(self.processed_input_data,
  File "c:\users\clowneylab\asoid\asoid\utils\extract_features.py", line 198, in feature_extraction
    binned_features = bsoid_extract_numba([train_datalist[i]], framerate)
  File "c:\users\clowneylab\asoid\asoid\utils\extract_features.py", line 189, in bsoid_extract_numba
    features = fast_feature_extraction(data, fps, index * 2, smooth)
  File "C:\Users\clowneylab\.conda\envs\asoid-test\lib\site-packages\numba\core\dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\clowneylab\.conda\envs\asoid-test\lib\site-packages\numba\core\dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
non-precise type reflected list(array(pyobject, 2d, C))<iv=None>
During: typing of argument at c:\users\clowneylab\asoid\asoid\utils\extract_features.py (153)

File "asoid\asoid\utils\extract_features.py", line 153:
def fast_smooth(data, n):
    <source elided>

@jit(nopython=True)
```

I tried to test with calms21 dataset and there is no issue with that. 

I'm really looking forward to trying A-soid out as it will make behavior analysis much more easier. I appreciate you for troubleshooting with me a lot!

**Comment by njb615** [comment]
> Hello @JensBlack & @runninghsus, I was able to successfully perform the extract features step using the test/train calms21 .npy files. ![image](https://user-images.githubusercontent.com/22827738/257579917-5e13adb2-37e4-4296-b9bb-6f8d1c9e99fc.png)
> 
> I have attempted the feature extraction after uploading a boris binary events csv file that fills the entire length of the video but I get the exact same error. Here's the updated binary csv for reference; [binary_fLength.csv](https://github.com/YttriLab/A-SOID/files/12262682/binary_fLength.csv)
> 
> I have a question that may be related to my issue -- when I preprocess my data, I get the following message: "Processed a total of 1 .csv files, and compiled into a (1, 922, 14) data list." Since A-SOiD needs two csv files (e.g. deeplabcut & boris) does it mean that there's an issue processing one of the csv files I upload and maybe thats causing the error at the extract features step?
> 
> Additionally, do you have any sample DeepLabCut & Boris files so that I can check if there's a discrepancy between how mine are structured compared to a working example? Clearly there isn't an issue with numba when I use the calms21 .npy files but for some reason the data in my csv files is not being stored in numpy arrays the right way. I tried your load_dlc_data() function from the import_data.py file and it seems that its reading all values as float64, which should be okey? Does A-SOiD only work with integers? <img alt="" width="50%" height="50%" src="https://user-images.githubusercontent.com/22827738/258532506-abf3b9d6-8b75-4812-b337-e8b3de49358f.png">

Our lab has also run into this issue. We can confirm (WindowsOS) that this error still pops up after ensuring the boris file begins at 0.
