### ISSUE TITLE
failed to build for numba, llvmlite on Silicon Mac (14.1.1)

### ISSUE THREAD

**Issue by mauricev** [YttriLab/A-SOID#53]
We are trying to install on an Silicon Mac running 14.1.1 and the installation fails with 

Failed to build for numba, llvmlite.

Conda was updated to the latest version prior to attempting the installation, version 23.10.0.

Here is the exact error message

```
  Building wheel for numba (setup.py): started
  Building wheel for numba (setup.py): finished with status 'error'
  Running setup.py clean for numba
  Building wheel for llvmlite (setup.py): started
  Building wheel for llvmlite (setup.py): finished with status 'error'
  Running setup.py clean for llvmlite
Failed to build numba llvmlite

Pip subprocess error:
WARNING: asoid 0.3 does not provide the extra 'dev'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/x3/cqrzt9j131z9_nrwm1978hg80000gn/T/pip-install-dod_y7c2/numba_a3ac1068e10f408cada6d42b97319f07/setup.py", line 413, in <module>
          metadata['ext_modules'] = get_ext_modules()
        File "/private/var/folders/x3/cqrzt9j131z9_nrwm1978hg80000gn/T/pip-install-dod_y7c2/numba_a3ac1068e10f408cada6d42b97319f07/setup.py", line 148, in get_ext_modules
          import numpy.distutils.misc_util as np_misc
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numba
  error: subprocess-exited-with-error
```

**Comment by tusharora9** [comment]
Building wheels for collected packages: numba, llvmlite
  Building wheel for numba (setup.py): started
  Building wheel for numba (setup.py): finished with status 'error'
  Running setup.py clean for numba
  Building wheel for llvmlite (setup.py): started
  Building wheel for llvmlite (setup.py): finished with status 'error'
  Running setup.py clean for llvmlite
Failed to build numba llvmlite

Pip subprocess error:
WARNING: asoid 0.3 does not provide the extra 'dev'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/x3/cqrzt9j131z9_nrwm1978hg80000gn/T/pip-install-dod_y7c2/numba_a3ac1068e10f408cada6d42b97319f07/setup.py", line 413, in <module>
          metadata['ext_modules'] = get_ext_modules()
        File "/private/var/folders/x3/cqrzt9j131z9_nrwm1978hg80000gn/T/pip-install-dod_y7c2/numba_a3ac1068e10f408cada6d42b97319f07/setup.py", line 148, in get_ext_modules
          import numpy.distutils.misc_util as np_misc
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numba
  error: subprocess-exited-with-error
  
  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/x3/cqrzt9j131z9_nrwm1978hg80000gn/T/pip-install-dod_y7c2/numba_a3ac1068e10f408cada6d42b97319f07/setup.py", line 413, in <module>
          metadata['ext_modules'] = get_ext_modules()
        File "/private/var/folders/x3/cqrzt9j131z9_nrwm1978hg80000gn/T/pip-install-dod_y7c2/numba_a3ac1068e10f408cada6d42b97319f07/setup.py", line 148, in get_ext_modules
          import numpy.distutils.misc_util as np_misc
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for numba
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      running bdist_wheel
      /Users/tusharora9/anaconda3/envs/asoid/bin/python /private/var/folders/x3/cqrzt9j131z9_nrwm1978hg80000gn/T/pip-install-dod_y7c2/llvmlite_d1c5e4399a384659943f9b94a2bef773/ffi/build.py
      LLVM version... Traceback (most recent call last):
        File "/private/var/folders/x3/cqrzt9j131z9_nrwm1978hg80000gn/T/pip-install-dod_y7c2/llvmlite_d1c5e4399a384659943f9b94a2bef773/ffi/build.py", line 105, in main_posix
          out = subprocess.check_output([llvm_config, '--version'])
        File "/Users/tusharora9/anaconda3/envs/asoid/lib/python3.8/subprocess.py", line 415, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/Users/tusharora9/anaconda3/envs/asoid/lib/python3.8/subprocess.py", line 493, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/Users/tusharora9/anaconda3/envs/asoid/lib/python3.8/subprocess.py", line 858, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/Users/tusharora9/anaconda3/envs/asoid/lib/python3.8/subprocess.py", line 1720, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/private/var/folders/x3/cqrzt9j131z9_nrwm1978hg80000gn/T/pip-install-dod_y7c2/llvmlite_d1c5e4399a384659943f9b94a2bef773/ffi/build.py", line 191, in <module>
          main()
        File "/private/var/folders/x3/cqrzt9j131z9_nrwm1978hg80000gn/T/pip-install-dod_y7c2/llvmlite_d1c5e4399a384659943f9b94a2bef773/ffi/build.py", line 185, in main
          main_posix('osx', '.dylib')
        File "/private/var/folders/x3/cqrzt9j131z9_nrwm1978hg80000gn/T/pip-install-dod_y7c2/llvmlite_d1c5e4399a384659943f9b94a2bef773/ffi/build.py", line 107, in main_posix
          raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
      RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
      error: command '/Users/tusharora9/anaconda3/envs/asoid/bin/python' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llvmlite
ERROR: Could not build wheels for numba, llvmlite, which is required to install pyproject.toml-based projects

failed

CondaEnvException: Pip failed

**Comment by tusharora9** [comment]
Hi @JensBlack @runninghsus 

Thanks for taking a look at this.
I tried installing this on an Intel Mac running OS - Monterey (12.6.5) as well and it went flawlessly.

I'm wondering if this is an issue only with Silicon (M1/M2) Macs since these have different internal architecture.
I don't have any issues with building numba and llvmlite on my system though, as I tried different versions of LLVM packages to get this resolved. But all resulted in the same error.

**Comment by JensBlack** [comment]
Thanks for reporting back! Glad to see that normal MacOs works on your side as well.

If you manage to find out what caused the issue, it would be great if you could report back so other users can benefit from this!

I'll leave this open for now.

**Comment by JensBlack** [comment]
We had another user from our labs try this on a similiar system and they found a solution for now:

> I have a MacBook Pro M2, 2022. I also have Sanoma 14.1.2 installed. After working on this I did get A-SOID app to open. 
>Heres the link which was most informative: https://numba.readthedocs.io/en/stable/user/installing.html#installing-on-linux-armv8-aarch64-platforms. However for certain dependencies only certain versions work with Linux/Silicon Apple Chips. 
[...]
>The Fix that I used:
>1)Clone repository
>2) going into the requirements.txt file and changing numba to 0.55.1 it was originally 0.52.0 
>3) go to path 
>4) conda activate envs 
>5) asoid app


This requires a version change of numba to 0.55.1 in the requirements.txt file before installation. I will test whether there are any reasons that we shouldn't generally update to that version and then upload the new requirements asap.

in the meantime, it would be great if you could verify whether this works on your end as well and report back to us.
for this:
1. Download the latest version of the asoid repository (or clone it)
2. Unpack and open requirements.txt
3. Change the line `numba~=0.52.0` to `numba==0.55.1`
4. Continue following the normal installation steps
5. Report back to us if it worked :)

[Link from above](https://numba.readthedocs.io/en/stable/user/installing.html#installing-on-linux-armv8-aarch64-platforms)

**Comment by JensBlack** [comment]
Fixed version issue with latest update to requirements.txt and extended the step-by-step guide for Mac users.

[Docs](https://github.com/YttriLab/A-SOID/blob/main/docs/installation_stepbystep.md)
